### ISSUE TITLE
Extend Readme

### ISSUE THREAD

**Issue by miralem-cebic** [S3cur3Th1sSh1t/EmpEISDecrypt#1]
Dear Source Code Maintainer,

as Product Manager of Matrix42 Secure Unified Endpoint Management, I would like to ask you, if it is possible to extend the Readme file of this repo with the information that Matrix42 as the vendor of Client Lifecycle Management Suite Empirum providing to customers a security hardening guide for years. The information is provided by Matrix42 Support. 
Matrix42 Customers, Partners, and I would really appreciate it if you could add this general information to your Readme to make it transparent. 

If want to get in contact with me about how we can provide this information in general, please drop me a mail to: miralem.cebic@matrix42.com

Best regards
Miralem

**Comment by S3cur3Th1sSh1t** [comment]
Hey,

sure I can add this information. Can you provide a link to the hardening guide or is this classified as internal? 

Greetings

**Comment by S3cur3Th1sSh1t** [comment]
Is this - 828268e2a56ca8f93369680bec122eb9e8ba2f21 - fine for you?

**Comment by S3cur3Th1sSh1t** [comment]
If you are looking for more information in the readme feel free to reopen the issue.
